### ISSUE TITLE
'maximize/restore split' action is missing

### ISSUE THREAD

**Issue by igorwojda** [dkandalov/tab-shifter#13]
Docs mention this, but no option in menu, no action in Keymap

**Comment by durandom** [comment]
Its been added in https://github.com/dkandalov/tab-shifter/pull/11 which is v0.26 which is not released yet. @dkandalov could you release the new version?

**Comment by dkandalov** [comment]
@durandom yes, although IIRC the was a problem with maximize/restore that it didn't fully maximize tab.

**Comment by sttts** [comment]
@dkandalov that's the maximum/minimum that Idea allows afaik.

**Comment by dkandalov** [comment]
@durandom @sttts I guess you mean using `com.intellij.openapi.ui.Splitter#setProportion`, but there might be other ways. There are also couple problems with current implementation:
 - it hides but doesn't restore toolwindows
 - it doesn't maximize nested splitters

**Comment by sttts** [comment]
Also it only works if there is a split.

**Comment by fatfatson** [comment]
still not release??

**Comment by dkandalov** [comment]
Sorry, @fatfatson it's been a while :(
The main reason I didn't release is that current maximise/minimise doesn't do it "properly". Although maybe I should just release it the way it is 🤔
