### ISSUE TITLE
move tab right/left does not work when 'Distraction free mode' is enabled

### ISSUE THREAD

**Issue by igorwojda** [dkandalov/tab-shifter#14]
I can do it before going to 'Distraction free mode', but when I hide the last tab on the side, it's not possible to recreate split again

**Comment by dkandalov** [comment]
I can confirm it wasn't properly working IJ 2017.2.
It seems to work fine though in IJ 2019.3.
I assume it was some limitation of IDE api which has been fixed since then.

Sorry for replying soooo late :(
