### ISSUE TITLE
Pinned tab loses pinned status when whone to another pane / splitter.

### ISSUE THREAD

**Issue by momomo** [dkandalov/tab-shifter#21]
Pinned tab loses pinned status when whone to another pane / splitter. Big issue.

**Comment by dkandalov** [comment]
Thank you for reporting this. 
It should be fixed in plugin version 0.28.

**Comment by momomo** [comment]
Hmm, I am running 0.29 and seems it is not remembering the pinned status when moving a tab from one splitter to another. Have restarted IJ.

**Comment by momomo** [comment]
You seem to have fixed it when splitting, but there is move as well, back and forth.

**Comment by dkandalov** [comment]
Fixed in the commit above.

The pinning was broken for both splitting and move (after fixing issue #22).
It worked in some cases only because of how IJ creates a new splitter.

**Comment by momomo** [comment]
Is there a new build out now with the fix?

**Comment by momomo** [comment]
shift right / left / up / down is not retaining pinned status.

**Comment by dkandalov** [comment]
This should be fixed in version 0.30.

**Comment by momomo** [comment]
I just tried quickly and seems to work. I will let you know if there are any corner cases! Great job!
