### ISSUE TITLE
Extension does not work in Beta UI

### ISSUE THREAD

**Issue by PascalSenn** [dkandalov/tab-shifter#28]
Hi there,

Thanks for your efforts in creating this extension. It has become part of my core editing workflow.

I am currently trying out the new Beta UI in rider EAP 2022.3. Love the new UI, but i have the problem that tab shifter no longer works. 

Could it be that they changed the API and some changes are needed to make it work again?

**Comment by dkandalov** [comment]
Hi! Yes, it is very likely the case.

Unfortunately, I'm not using this plugin very often 🙈 and I'm staying away from new UI for now, so probably won't look into the issue very soon. Any help is welcome 🙂

**Comment by PascalSenn** [comment]
Hi @dkandalov  
I completley understand! i also wonder why this has to be a extension and not a native IDE feature. Dont get me wrong, i love this extension. i use it a every day as part of my core workflow with IDEAVIM. 
VSCode for example would theoretically support it natively, so why does idea not support it.
I opened an issue on youtrack for it!
https://youtrack.jetbrains.com/issue/IDEA-304522/Implement-Tab-Shifter-functionality
Thanks for you work on this extension! you really make my life easier with it

**Comment by dkandalov** [comment]
I just tried the plugin with the new UI in the latest EAP and it seems to work ok 🤔

**Comment by PascalSenn** [comment]
@dkandalov  AMAZING! IT WORKS IN THE BETA UI!

Thanks a lot for your help! My workflow is saved!
