### ISSUE TITLE
Feature: option to make focus follow moved window

### ISSUE THREAD

**Issue by huyz** [dkandalov/tab-shifter#29]
It would be nice if there were an option to have vscode behavior: the focus stays in the moved window when doing "Shift X".  That way I can hit shortcuts in succession to move the window several time (e.g., from the top-left corner to the bottom-right corner of a 2x2 grid)

**Comment by dkandalov** [comment]
This is how it's supposed to work. Most likely this was broken by changes in IntelliJ implementation.

**Comment by huyz** [comment]
Dup of https://github.com/dkandalov/tab-shifter/issues/27
