### ISSUE TITLE
2024.2.0 EAP 7 - Move tab does no longer work

### ISSUE THREAD

**Issue by PascalSenn** [dkandalov/tab-shifter#40]
It seems like moving tabs directionally stopped working yet again with eap 7

**Comment by dkandalov** [comment]
Thank you for reporting this!
It should be fixed in plugin version 0.35
https://plugins.jetbrains.com/plugin/7475-tab-shifter/edit/versions/stable/572911

**Comment by PascalSenn** [comment]
Thank you!!
